### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SalahEddineBC** [lol768/Netflix-Bitrate-Override-Restore#2]
Hello   
I installed this extension , but it didnt work , i tried to reload the page/reopen chrome but still facing the problem , but before i got to install it i had to change the persistance value in manifest.json to true because i had this problem : The 'webRequest' API cannot be used with event pages. and i used this solution to install it https://stackoverflow.com/questions/13326105/using-webrequest-api-with-event-page , can you tell me what i am doing wrong   
Thank You for this awsome extension!

**Comment by SalahEddineBC** [comment]
I just noticed that is firefox extension lol , you should mention that tho

**Comment by lol768** [comment]
![](https://lol768.com/i/CheeringIntroducedQuarantinesShaykhs)

**Comment by lol768** [comment]
To clarify, it's not deliberately written in a way that limits it to Firefox but reality is that Chrome & Edge haven't implemented the APIs I use yet:

![](https://lol768.com/i/PeculiarlyDebarGruyeresNanotechnology)

I discussed this a bit more in #1

**Comment by SalahEddineBC** [comment]
well , my bad , i didnt take a look on release page sorry

**Comment by lol768** [comment]
You may want to take a look at https://github.com/truedread/netflix-1080p which will give you the bitrate menu and also unlock access to 1080p content in Chrome, @SalahEddineBC

**Comment by SalahEddineBC** [comment]
Thanks i will take a look , waiting for the support of the API that you used

**Comment by psvita123** [comment]
@SalahEddineBC  are you able to use this extension on Microsoft Edge?
